<?php

$widgetEditor = new CHTMLEditor();
$widgetEditor->Show(array(
	'name' => $strHTMLControlName["VALUE"],
	'id' => $strHTMLControlName["VALUE"],
	'inputName' => $strHTMLControlName["VALUE"],
	'content' => $value["VALUE"],
	'width' => '100%',
	'minBodyWidth' => !empty($field["COLS"])? $field["COLS"] : 500,
	'normalBodyWidth' => !empty($field["COLS"])? $field["COLS"] : 500,
	'height' => !empty($field["ROWS"])? $field["ROWS"] : 200,
	'bAllowPhp' => false,
	'limitPhpAccess' => false,
	'autoResize' => true,
	'autoResizeOffset' => 40,
	'useFileDialogs' => false,
	'saveOnBlur' => true,
	'showTaskbars' => false,
	'showNodeNavi' => false,
	'askBeforeUnloadPage' => true,
	'bbCode' => false,
	'siteId' => SITE_ID,
	'controlsMap' => array(
		array('id' => 'Bold', 'compact' => true, 'sort' => 80),
		array('id' => 'Italic', 'compact' => true, 'sort' => 90),
		array('id' => 'Underline', 'compact' => true, 'sort' => 100),
		array('id' => 'Strikeout', 'compact' => true, 'sort' => 110),
		array('id' => 'RemoveFormat', 'compact' => true, 'sort' => 120),
		array('id' => 'Color', 'compact' => true, 'sort' => 130),
		array('id' => 'FontSelector', 'compact' => false, 'sort' => 135),
		array('id' => 'FontSize', 'compact' => false, 'sort' => 140),
		array('separator' => true, 'compact' => false, 'sort' => 145),
		array('id' => 'OrderedList', 'compact' => true, 'sort' => 150),
		array('id' => 'UnorderedList', 'compact' => true, 'sort' => 160),
		array('id' => 'AlignList', 'compact' => false, 'sort' => 190),
		array('separator' => true, 'compact' => false, 'sort' => 200),
		array('id' => 'InsertLink', 'compact' => true, 'sort' => 210),
		array('id' => 'InsertImage', 'compact' => false, 'sort' => 220),
		array('id' => 'InsertVideo', 'compact' => true, 'sort' => 230),
		array('id' => 'InsertTable', 'compact' => false, 'sort' => 250),
		array('separator' => true, 'compact' => false, 'sort' => 290),
		array('id' => 'Fullscreen', 'compact' => false, 'sort' => 310),
		array('id' => 'More', 'compact' => true, 'sort' => 400)
	),
));
